bio_web_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resource :root, only: [:index]

  resources :hamming_distance_calculation, only: [:new] do
    collection do
      post :calculate
    end
  end
  

  root "root#index"
end

bio_web_app/app/models/hamming_distance_calculation.rb
class HammingDistanceCalculation 
  include ActiveModel::Model

  attr_accessor :dna_strand_1, :dna_strand_2
end

bio_web_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bio_web_app/app/controllers/hamming_distance_calculation_controller.rb
class HammingDistanceCalculationController < ApplicationController
  def new
    @calculation = HammingDistanceCalculation.new
  end

  def calculate
    @message = hamming_result(params)
  end

  private

  def hamming_result(params)
    strand_1 = params[:hamming_distance_calculation][:dna_strand_1]
    strand_2 = params[:hamming_distance_calculation][:dna_strand_2]
    "Result: #{Hamming.compute(strand_1, strand_2)}"
  rescue ArgumentError
    'Incorrect input'
  end
end

bio_web_app/app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

bio_web_app/app/helpers/application_helper.rb
module ApplicationHelper
end

bio_web_app/app/views/hamming_distance_calculation/calculate.html.erb
<p>
<%= @message %>
</p> 

bio_web_app/app/views/hamming_distance_calculation/new.html.erb
<%= form_for @calculation, url: { action: :calculate } do |f| %>
  <p>
    <%= f.label(:dna_strand_1, "First DNA strand") %>
    <%= f.text_field(:dna_strand_1) %>
  </p>

  <p>
    <%= f.label(:dna_strand_2, "Second DNA strand") %>
    <%= f.text_field(:dna_strand_2) %>
  </p>

  <%= f.submit "Calculate" %>
<% end %> 

bio_web_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BioWebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

bio_web_app/app/views/root/index.html.erb
<%= link_to "Calculate Hamming Distance", new_hamming_distance_calculation_path  %> 